# Generated by Django 3.2.5 on 2022-01-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment_category',
            new_name='EquipmentCategory',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='published',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='item',
            name='puk',
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('puk', models.CharField(blank=True, max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=24)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_phone', to='inventory.item')),
            ],
        ),
    ]
