# Generated by Django 3.2.5 on 2022-01-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220117_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='item',
        ),
    ]
