# Generated by Django 3.2.5 on 2022-01-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_mobilephone_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_phone', to='inventory.item'),
        ),
    ]
